// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schemas

import "encoding/json"
import "fmt"
import "regexp"

type Category struct {
	// Format corresponds to the JSON schema field "format".
	Format *string `json:"format,omitempty,omitzero" yaml:"format,omitempty" mapstructure:"format,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id Id `json:"id" yaml:"id" mapstructure:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Category) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Category: required")
	}
	type Plain Category
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Category(plain)
	return nil
}

type Id string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Id) UnmarshalJSON(value []byte) error {
	type Plain Id
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^\d{17,20}$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^\d{17,20}$`)
	}
	*j = Id(plain)
	return nil
}

type PropCategory struct {
	// Category corresponds to the JSON schema field "category".
	Category Category `json:"category" yaml:"category" mapstructure:"category"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PropCategory) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["category"]; raw != nil && !ok {
		return fmt.Errorf("field category in PropCategory: required")
	}
	type Plain PropCategory
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PropCategory(plain)
	return nil
}

type PropChannel struct {
	// Channel corresponds to the JSON schema field "channel".
	Channel Id `json:"channel" yaml:"channel" mapstructure:"channel"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PropChannel) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channel"]; raw != nil && !ok {
		return fmt.Errorf("field channel in PropChannel: required")
	}
	type Plain PropChannel
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PropChannel(plain)
	return nil
}

type PropWebhook struct {
	// Webhook corresponds to the JSON schema field "webhook".
	Webhook Webhook `json:"webhook" yaml:"webhook" mapstructure:"webhook"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PropWebhook) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["webhook"]; raw != nil && !ok {
		return fmt.Errorf("field webhook in PropWebhook: required")
	}
	type Plain PropWebhook
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PropWebhook(plain)
	return nil
}

type SchemaJson struct {
	// Children corresponds to the JSON schema field "children".
	Children SchemaJsonChildren `json:"children,omitempty,omitzero" yaml:"children,omitempty" mapstructure:"children,omitempty"`
}

type SchemaJsonChildren map[string]interface{}

type Webhook string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Webhook) UnmarshalJSON(value []byte) error {
	type Plain Webhook
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^https:\/\/discord\.com\/api\/webhooks\/\d{17,20}\/[a-zA-Z0-9._-]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^https:\/\/discord\.com\/api\/webhooks\/\d{17,20}\/[a-zA-Z0-9._-]+$`)
	}
	*j = Webhook(plain)
	return nil
}
